---
title: "Untitled"
output: html_document
---

```{r}
library(lubridate)
library(tidyr)
library(dplyr)
library(ggplot2)

round1Dir <- "\\\\Lindfs12\\home$\\cfleit\\My Documents\\My papers\\2013-LucernePasture\\kl\\submitted\\round_1" # for graphs

```


```{r}
info <- read.table("K:\\CPDiary\\Data\\Lucerne & pasture drought trial 2011-2012\\Analysis\\Worked data\\Light interception\\CoverDataInterpHamish.txt", header=FALSE, skip=5)

# Using plot sequence used by Hamish as col names
plotSeqHamish <-  c("Date",1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 3, 30, 31, 32, 4, 5, 6, 7, 8, 9)

colnames(info) <- as.character(plotSeqHamish)

info$Date <- ymd(info$Date)

summary(info) 
#str(info) 



```

```{r}
# get treat names
plotLabels <- read.table("K:\\CPDiary\\Data\\Lucerne & pasture drought trial 2011-2012\\Analysis\\TreatLabelsForR.txt", header=TRUE)

head(plotLabels, nrow(plotLabels))


```

```{r}
# re-arrange and merge
workDF <- info %>%
  tidyr::gather("Plot","CoverValue", 2:ncol(info)) %>%
  merge(plotLabels, by= "Plot") %>%
  mutate(Rep = as.factor(Rep)) %>%
  mutate(Plot = as.factor(Plot)) %>%
  mutate(Irrig = factor(Irrig,levels=c("Rain-fed", "Low", "Medium", "High")))

head(workDF)
```

```{r}
summary(workDF)
```

## get measured points
```{r}
cover_meas <- read.table("C:\\GitHubRepos\\LP_analysis\\CoverMeasuredData.txt", header = TRUE)

summary(cover_meas)
```
# do average and sd
```{r}
cover_meas_av <- cover_meas %>%
  mutate(Date = dmy(Date)) %>%
  mutate(Irrig = factor(Irrig, 
                        levels=c("Rain","Low","Med","High"),
                        labels=c("Rain-fed","Low frequency","Medium frequency","High frequency"))) %>%
  group_by(Date, Crop, Irrig) %>%
  dplyr::select(-Plot,-Block) %>%
  summarise_each(funs(mean, sd))

summary(cover_meas_av)
```

```{r}
# interpolated averages
cover_int_av <- workDF %>%
  mutate(Date=ymd(Date)) %>%
  mutate(Irrig = factor(Irrig, 
                        levels=c("Rain-fed","Low","Medium","High"),
                        labels=c("Rain-fed","Low frequency","Medium frequency","High frequency"))) %>%
  mutate(Crop = Species) %>%
  dplyr::select(-Species)%>%
  group_by(Date, Crop, Irrig) %>%
  summarise(CoverValue = mean(CoverValue)) 
  

summary(cover_int_av)
```

# graph

```{r, warning=FALSE}

# graph
g <- cover_meas_av %>%
  ggplot(aes(x=Date,y=mean, colour=Irrig, shape=factor(Irrig))) +
  geom_point() +
  scale_shape(solid = FALSE) +
  facet_grid(Crop~.) +
  ylab("Canopy cover (fractional)") +
  labs(colour="Water supply\n treatment") +
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2), width = 2) +
  geom_line(data=cover_int_av, aes(x=Date,y=CoverValue),size=1.0, alpha=0.5) + guides(shape=FALSE)

g

# Save
 round1Dir <- "\\\\Lindfs12\\home$\\cfleit\\My Documents\\My papers\\2013-LucernePasture\\kl\\submitted\\round_1"
 ggsave(file="Fig_2_cover.tiff", dpi = 300, path=round1Dir, g)

```

Table of average values

```{r}
workDF %>%
  group_by(Species,Irrig) %>%
  na.omit() %>%
  summarise(Cover_av = median(CoverValue), 
            Q_range = (quantile(CoverValue,0.75)-quantile(CoverValue,0.25))) %>%
  kable(digits=2)

```
## Do anova
```{r}
crops <- unique(workDF$Species)

for (c in 1:length(crops)) {
  
df <- workDF %>% filter(Species == crops[c])
  
anova <- aov(CoverValue ~ Irrig+Rep, data = df )
print("##################################")
print(paste0("##### Crop: ",crops[c], "    ###########"))
print("##################################")
print(summary(anova))
print(TukeyHSD(anova))

a <- HSD.test(anova, "Irrig")
print(a)
  
}
```

