---
title: "Untitled"
output: html_document
---
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(agricolae)
library(knitr)
```

```{r}
info <- read.table("C:\\GitHubRepos\\LP_analysis\\BiomassAnnualRawData.txt", header=TRUE)

info <- info %>%
  mutate(Rep = factor(Rep)) %>%
  mutate(Irrigation = factor(Irrigation, levels=c("Hig", "Med", "Low", "Dry"))) %>%
  mutate(Season = as.factor(paste0("Season ",Season))) %>%
  mutate(Season = factor(Season))

summary(info)
```

```{r}
str(info)
```

```{r Check, fig.height=10}

info %>%
  tidyr::gather("Variable", "Value", 5:6) %>%
  group_by(Crop, Season, Irrigation, Variable) %>%
  dplyr::select(-Rep) %>%
  ggplot(aes(x=Irrigation, y=Value)) +
  #geom_bar(stat="identity") + 
  geom_boxplot(alpha=0.1) +
  geom_jitter(width=0.1) +
  facet_grid(Variable+Crop~Season, scales = "free") +
  xlab("Irrigation frequency") +
  ylab("Water use (mm/year)                      Crop yield (t/ha/year)") +
  theme(text = element_text(size=20))
```

```{r}

SumData <- info %>%
  group_by(Crop, Irrigation, Rep) %>%
  summarise(Yield = mean(Yield_tHa), WaterUse = mean(waterUse_mmYear), WUE=Yield*1000/WaterUse) 

summary(SumData)
  
```

## Do ANOVA

```{r}

crops <- unique(SumData$Crop)

for (c in 1:length(crops)) {
  
df <- SumData %>% filter(Crop == crops[c])
  
anova <- aov(Yield ~ Irrigation+Rep, data = df )
print("##################################")
print(paste0("##### Crop: ",crops[c], "    ###########"))
print("##################################")
print(summary(anova))
print(TukeyHSD(anova))

a <- HSD.test(anova, "Irrigation")
print(a)
  
}

```

```{r}

str(SumData)

tableSum <- SumData %>%
  ungroup() %>% # need it!
#  tidyr::gather("Variable", "Value", Yield:WaterUse) %>%
  group_by(Crop, Irrigation) %>%
  dplyr::select(Crop, Irrigation, Yield) %>%
 # mutate(Variable = factor(Variable)) %>%
 # group_by(Crop,Variable, Rep, Irrigation) %>%
  summarise(MeanValue = mean(Yield), SdValue = sd(Yield))


```

## Show as Table

```{r}
tableSum %>%
  kable(format = "markdown", digits = 2)
```

## Graph for paper

```{r, fig.height=10, fig.width=12}

# late fix of labels
info_work <- info %>% 
  # mutate(Season = factor(Season,levels=c("Season 1","Season 2","Season 3"),
  #                               labels= c("2012","2013","2014"))) %>%
                      mutate(Irrigation = factor(Irrigation, 
                                                    levels=c("Dry","Low","Med","Hig"),
                                                    labels= c("No","Low","Medium", "High"))) # re-order factors


g<-info_work %>%
  tidyr::gather("Variable", "Value", 5:6) %>%
  group_by(Crop, Season, Irrigation, Variable) %>%
  dplyr::select(-Rep) %>%
  filter(Variable=="Yield_tHa") %>%
  summarise_all(funs(mean,sd)) %>%
  ggplot(aes(x=Irrigation, y=mean)) +
  geom_bar(stat="identity") + 
 # geom_boxplot(alpha=0.1) +
#  geom_jitter(width=0.1) +
  facet_grid(Crop~Season, scales = "free") +
  xlab("Irrigation frequency") +
  ylab("Forage dry matter yield\n (t DM/ha per year)") +
  theme(text = element_text(size=20)) +
    geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9)) +
  theme(axis.text.x=element_text(angle=45, hjust=1))
g

# save it for the sensitivity analysis
#saveDir <- "C:\\GitHubRepos\\LP_analysis\\"
saveDir <- "\\\\Lin-file\\home$\\cfleit\\My Documents\\My papers\\2013-LucernePasture\\kl\\submitted\\round_6"
ggsave(file="Fig_BiomassSeasonal.tiff", dpi = 300, path=saveDir, g)
```

