---
title: "MetFileAnalysis"
author: "edmar.teixeira@me.com"
date: "Friday, March 27, 2015"
output: html_document
---

!!!!!!!!!!!!!!!!!!! UNFINISHED

## Reads met files from apsim (based on MapOutApsimFiles.R)
## Creates a dataframe with column row

```{r Libs, echo = FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
library(gridExtra)
library(lubridate)
library(scales)
```

## The weather file

> That's how the data looks like

```{r DirSet, echo=FALSE}

#Set paths
#setwd("C:\\Apsim_dev\\Projects\\Forage_MBIE(FRNL)\\ModelStudies")
metFolder <- "C:\\Apsim_dev\\Data\\MetFiles\\"

# Get file
metFile <- read.table(paste0(metFolder,"lincoln.met"), skip = 6, header = TRUE, comment.char = "(", blank.lines.skip = TRUE)

metFile <- data.frame(metFile)

# create a date
metFile$Date <- as.Date(paste(metFile$year, metFile$day , sep = "." )  , format = "%Y.%j" )
metFile$Month <- as.numeric(month(metFile$Date))

```

```{r}
summary(metFile)
```

# Graph historical averages

> Daily temperaure and radiation

> Monthly rainfall

> Pooled for 30 years

```{r GraphMet, echo = FALSE, fig.width=12, fig.height=10}

baseDate <- ymd("2011-01-15 UTC")

fontSize <- 15

# historical data df --------------------------------
weather_hist <- metFile %>%
  filter(year %in% 1960:2010) %>%
  group_by(Month) %>%
  summarise_each(funs(mean, sd)) %>%
  as.data.frame()

# place holder for 4 similar sets of annual historical averages
df_exp_temp <- weather_hist[rep(row.names(weather_hist), 4), 1:ncol(weather_hist)]
df_exp_temp$Month <- c(1:nrow(df_exp_temp)) # number the months sequentially

# create mid-point "mock dates" for trial period
weather_hist.expanded <- df_exp_temp %>%
  mutate(BaseDate = ymd(baseDate)) %>%
  mutate(Date =  BaseDate %m+% months(Month-1)) %>% # creates dates starting from base and adding the number of months 
  dplyr::select(-BaseDate,-year_mean)

summary(weather_hist.expanded)

```
# test
```{r}
weather_hist.expanded %>%
  ggplot(aes(x=Date, y=maxt_mean)) +
  geom_line()
```

# do a daily historical average
```{r}
weather_day_avg <- metFile %>%
  filter(year %in% 1960:2010) %>%
#  mutate(DOY = yday(Date)) %>% # days of year
  group_by(day) %>%
  dplyr::select(day:vp) %>%
  summarise_each(funs(mean)) %>%
#  mutate(Day = as.integer(day_mean))%>%
  as.data.frame()

summary(weather_day_avg)
```

```{r}

# FIXME: NOT working yet 

# place holder for multiplied historical averages
df_exp_temp <- weather_day_avg[rep(row.names(weather_day_avg), 4), 1:ncol(weather_day_avg)]
df_exp_temp$Month_mean <- c(1:nrow(df_exp_temp)) 

# create mid-point "mock dates" for trial period
weather_day.expanded <- df_exp_temp %>%
  mutate(BaseDate = ymd(baseDate)) %>%
  mutate(Date =  BaseDate %m+% months(Month_mean-1)) %>%
  dplyr::select(-BaseDate,-year_mean)

summary(weather_day.expanded)
```



# plot for period of trials
```{r}
weather_trial <- metFile %>%
  filter(year %in% 2011:2014) %>%
  as.data.frame()

summary(weather_trial)
```



```{r,fig.width=12, fig.height=8, warning=FALSE}



# maxt
g1 <- weather_trial %>%
  ggplot(aes(x=Date, y=maxt))  +
  geom_point(colour= "darkblue", alpha=0.3) +
  geom_line(data=weather_hist.expanded, 
            aes(x=Date, y=maxt_mean), colour="black") +
 # theme_bw() +
  xlab("Date") + 
  ylab("Daily maximum temperature (oC)") +
  ylab(expression("Daily maximum temperature ( "*degree*C*")")) +
  theme(text = element_text(size=fontSize)) 

#mint
g2 <- weather_trial %>%
  ggplot(aes(x=Date, y=mint))  +
  geom_point(colour= "darkblue", alpha=0.3) +
  geom_line(data=weather_hist.expanded, 
            aes(x=Date, y=mint_mean), colour="black") +
 # theme_bw() +
  xlab("Date") + 
  ylab("Daily minimum temperature (oC)") +
  ylab(expression("Daily minimum temperature ( "*degree*C*")")) +
  theme(text = element_text(size=fontSize)) 

#radn
g3 <- weather_trial %>%
  ggplot(aes(x=Date, y=radn))  +
  geom_point(colour= "darkblue", alpha=0.3) +
  geom_line(data=weather_hist.expanded, 
            aes(x=Date, y=radn_mean), colour="black") +
 # theme_bw() +
  xlab("Date") + 
  ylab("Daily maximum temperature (oC)") +
#  ylab(expression("Daily maximum temperature ( "*degree*C*")")) +
 # ylab("Daily solar radiation (MJ/m2)" ) +
   ylab(expression(Daily~solar~radiation~~"(MJ "*m^"-2"*")")) +
   theme(text = element_text(size=fontSize))

# rain
weather_trial$month <- with(weather_trial, strptime(paste(year, day), format="%Y %j")$mon+1)

g4 <- weather_trial %>%
  group_by(year, month) %>%
  summarise_each(funs(sum)) %>%
  group_by(month) %>%
  select(month, rain) %>%
  summarise(rainMean = mean(rain), rainSd = sd(rain)/2) %>%
  ggplot(aes(x=month, y=rainMean)) + 
  geom_bar(stat ='identity') +
  theme_bw() +
 xlab("Month") + 
  ylab("Monthly rainfall (mm)") +
  scale_x_continuous(breaks=1:12) +
  geom_errorbar(aes(ymax = rainMean + rainSd, ymin=rainMean - rainSd), 
                position=position_dodge(width=0.9), width=0.25)+
  theme(text = element_text(size=fontSize))


grid.arrange(g1, g2, g3, nrow=2)
# Save
# ggsave(file="Fig_weather.tiff", dpi = 300)
```

```{r PotEvap_graph}

# Get file (simulated eo by APSIM - Pot ET for modsim paper)
theFile <- "C:\\Apsim_dev\\Projects\\Forage_MBIE(FRNL)\\ModelStudies\\05_CoverCropPaperSoils\\LightSoil EarlyCover ETPdaily.out"

etpFile <- read.table(theFile, skip = 3, header = TRUE, comment.char = "(", blank.lines.skip = TRUE)
head(etpFile)
tail(etpFile)
summary(etpFile)


#etpFile$Date <- as.Date(etpFile$Dat, format="%dd-%mm-%YYYY")

#etpFile$day <- yday(etpFile$Date)

#write.csv(etpFile, file = "test.csv")

summary(etpFile)

g5 <- etpFile %>%
  filter(year %in% 1960:2000) %>%
   group_by(day_of_year) %>%
 # summarise_each(funs(mean)) %>%
  ggplot(aes(x=day_of_year, y=eo))  +
  geom_point(colour= "darkblue", alpha=0.2) +
  stat_smooth(level = 0.9, size = 1, colour="white") + 
  xlab("Day of the year (1-365)") + 
  ylab("Potential evapo-transpiration (mm)") +
  theme(text = element_text(size=fontSize))


g5 <- etpFile %>%
  filter(year %in% 1960:2000) %>%
  group_by(year, month) %>%
  summarise_each(funs(sum)) %>%
  group_by(month) %>%
  select(month, eo) %>%
  summarise(rainMean = mean(eo), rainSd = sd(eo)/2) %>%
  ggplot(aes(x=month, y=rainMean)) + 
  geom_bar(stat ='identity') +
  xlab("Month") + 
  ylab("Potential evapo-transpiration (mm)") +
  scale_x_continuous(breaks=1:12) +
  geom_errorbar(aes(ymax = rainMean + rainSd, ymin=rainMean - rainSd), 
                position=position_dodge(width=0.9), width=0.25)+
  theme(text = element_text(size=fontSize))

grid.arrange(g1, g3, g4, g5)

```


