---
title: "R Notebook"
output: html_notebook
---

```{r}
library(xtable)
library(knitr)
library(RSQLite)
library(lubridate)
library(stringr)
library(tidyr)
library(dplyr)
library(ggplot2)
library (hydroGOF)
library(scales)
library(GGally)
library(xtable)

#saveDir <- "\\\\Lindfs12\\home$\\cfleit\\My Documents\\My papers\\2013-LucernePasture\\kl\\submitted\\round_1" # for graphs
saveDir <- "\\\\Lin-file\\home$\\cfleit\\My Documents\\My papers\\2013-LucernePasture\\kl\\submitted\\round_6"
```

# Read observed data by replicate

```{r}
repRaw <- read.table("K:\\CPDiary\\Data\\Lucerne & pasture drought trial 2011-2012\\ModelFitting\\LP_SW_Replicate.txt", 
                    header = TRUE)
summary(repRaw)
```

```{r}
repWork <- repRaw %>%
  mutate(Date = dmy(Date), Depth = factor(Depth),Crop = factor(Crop),Irrigation = factor(Irrigation))%>%
  rowwise() %>% # This is important!!!!!
  mutate(Obs_av = (B1+B2+B3+B4)/4)%>%
  mutate(CI95_down = (Obs_av-3.182*(sd(c(B1,B2,B3,B4))/sqrt(4)))) %>% # FIXME: check with Esther how to
  mutate(CI95_up = (Obs_av+3.182*sd(c(B1,B2,B3,B4)/sqrt(4)))) 

# save
write.csv(repWork, "K:\\CPDiary\\Data\\Lucerne & pasture drought trial 2011-2012\\ModelFitting\\worked_observed_data.csv",row.names=FALSE)

```

# Embelish and improve factor names

```{r}
repWork$Depth <- gsub("D", "", repWork$Depth)
repWork$Depth <- factor(repWork$Depth, 
                         levels = c(7, 23, 30, 50, 70, 90, 110, 130, 150))
repWork$Depth <- as.factor(repWork$Depth)

# Create separate Establishment and Regrowth periods
estDate <- "2012-06-01" # FIXME: find a more functional criteria later

repWork$Stage <- as.factor(ifelse(repWork$Date<=estDate,"Establishment","Regrowth"))
# sort out irrigation treat names
repWork <- repWork %>% mutate(Irrigation = factor(Irrigation, 
                                                    levels=c("None", 
                                                             "ThreeWeekly",
                                                             "OnePerWeek",
                                                             "TwoPerWeek"))) # re-order factors
levels(repWork$Irrigation) <- c("No Irrigation",
                                 "Low Frequency",
                                 "Medium Frequency", 
                                 "High Frequency") # rename factors, attention to match!
# sort out crop names
repWork <- repWork %>% mutate(Crop=factor(Crop, levels=c("Lucerne", "Pasture"))) # re-order factors
levels(repWork$Crop) <- c("Lucerne","Ryegrass") # rename factors, attention to match!


# Check levels
levels(repWork$Depth)

# Check
#head(dataWork)
summary(repWork)
str(repWork)
summary(repWork)
```

 ## with all replicates
```{r, fig.height=20,fig.width=15, echo=FALSE}
repVar <- repWork %>%
  dplyr::select(Crop, Date, Irrigation,Depth, B1:Obs_av) %>%
  tidyr::gather("Rep","Obs",B1:Obs_av) %>% # FIXME: check names to be used in raw data
  mutate(Rep = factor(Rep, labels=c("Block 1", "Block 2", "Block 3", "Block 4", "Average"))) %>%
  filter(Rep != "Average") 


repVar %>% 
  ggplot(aes(x=Date, y=Obs)) +
  geom_point(aes(colour=factor(Rep)), alpha=0.5) +
  geom_point(data=repWork, aes(x=Date, y=Obs_av), shape=2, colour="black") +
  geom_line(data=repWork, aes(x=Date, y=CI95_down), linetype=22, colour="darkgrey") +
  geom_line(data=repWork, aes(x=Date, y=CI95_up), linetype=22, colour="darkgrey") +
  facet_grid(Depth~Crop+Irrigation) + 
 # ylab("Volumetric soil moisture (mm)") +
  labs(y=expression("Volumetric soil moisture "~(cm^{3}~cm^{-3})))+
  theme(text = element_text(size=15)) +
    labs(colour="Experiental replicate") + theme(legend.position="top")+
  geom_vline(xintercept = as.numeric(as.Date(ymd(estDate))), linetype=2) 
```

# check negative values

```{r}
x<-repVar  %>%
  filter(Obs < 0)

x
```

## only averages and both crops together

 ## with all replicates
```{r, fig.height=10,fig.width=8, echo=FALSE}
repVar <- repWork %>%
  dplyr::select(Crop, Date, Irrigation,Depth, B1:Obs_av) %>%
  tidyr::gather("Rep","Obs",B1:Obs_av) %>% # FIXME: check names to be used in raw data
  mutate(Rep = factor(Rep, labels=c("Block 1", "Block 2", "Block 3", "Block 4", "Average"))) %>%
  filter(Rep != "Average") 


g <- repVar %>% 
  ggplot(aes(x=Date, y=Obs)) +
#  geom_point(aes(colour=factor(Crop)), alpha=0.5) +
  geom_point(data=repWork, aes(x=Date, y=Obs_av,colour=factor(Crop)), shape=1, size=1.5) +
  geom_line(data=repWork, aes(x=Date, y=Obs_av,colour=factor(Crop)), linetype=2) +
#  geom_line(data=repWork, aes(x=Date, y=CI95_down), linetype=22, colour="darkgrey") +
#  geom_line(data=repWork, aes(x=Date, y=CI95_up), linetype=22, colour="darkgrey") +
  facet_grid(Depth~Irrigation) + 
 # ylab("Volumetric soil moisture (mm)") +
  labs(y=expression("Volumetric soil moisture "~(cm^{3}~cm^{-3})))+
  theme(text = element_text(size=15)) +
    labs(colour="Perennial crop type") + theme(legend.position="top")+
  geom_vline(xintercept = as.numeric(as.Date(ymd(estDate))), linetype=2) 

head(repWork)

g

ggsave(file="Fig_ObsData.tiff", dpi = 300, path=saveDir, g)

```

