---
title: "SensitivityLP"
output: html_document
---
```{r}
library(xtable)
library(knitr)
library(RSQLite)
library(lubridate)
library(stringr)
library(tidyr)
library(dplyr)
library(ggplot2)
library (hydroGOF)
library(scales)
library(GGally)
library(xtable)

options("scipen"=100, "digits"=4) # prints not in scientific notation
```

Read

```{r}
info <- read.csv("C:\\GitHubRepos\\FodderBeetRUE_2016\\workedData.csv", header=TRUE)

summary(info)
```

## Do ANOVA sensitivity analysis

- Esther's method



```{r}
df_av <- info %>%
  mutate_each_(funs(factor), c("Crop","Stage","Irrigation","SurfaceKl","KLReduction","RootFrontVelocity")) %>%
  mutate(simIndex = paste0(Crop,Stage,Irrigation)) %>%
  mutate(simIndex = as.factor(simIndex)) %>%
  group_by(Crop,Stage,Irrigation,simIndex,SurfaceKl,KLReduction,RootFrontVelocity) %>%
  dplyr::select(Pred) %>%
  summarise_each(funs(mean))

simIndexUnique <- unique(df_av$simIndex)

```

```{r}

si_df_final <- NULL
si_df_final_m <- NULL

for(i in 1:length(simIndexUnique)) {
  
  # do anova
  thisDf <- df_av %>% filter(simIndex == simIndexUnique[i])
  anova <- aov(Pred ~  SurfaceKl*KLReduction*RootFrontVelocity, data = thisDf)
  anovaTable <- summary(anova)
  
  # print(simIndexUnique[i])
  # print(summary(anova))
  
  # get vector with sums of squares
  anova_SS <- anovaTable[[1]]$'Sum Sq'
 #  anova_SS <- anovaTable[[1]]$'Mean Sq'# esther suggested SS to be used - test only
  
  # internal df to hold ss values
  df_ss <- NULL
  df_ss <- data.frame(SS = anova_SS)

  #retrieves row names and load into result df
  namesAnTab <- rownames(anovaTable[[1]])
  rownames (df_ss) <- gsub(" ","",namesAnTab) # remove spaces
  
  # get names and count of main factors
  mainFactNames <- rownames (df_ss)[-grep(':',rownames (df_ss))] # isolate the main factors from
  noFactors <- length(mainFactNames)  # counts row names that do not have ":" i.e. from interaction
 
 # Creates a column with "normalised" percent of total variation (SS) 
  df_ss$SS_p <- round((df_ss$SS/sum(df_ss$SS))*100,3)
  # df_ss$SS_p <- round((df_ss$MS/sum(df_ss$MS))*100,3) # esther suggested SS to be used - test only
  
  # Add SS of interections as a new vector element that adds to 100%
sumInt <- sum(df_ss$SS_p[(noFactors+1):length(namesAnTab)]) # Calculate sums total SS due to interactions (i.e. sums every SS that is not main factor)
si_Out1 <- c(df_ss$SS_p[1:noFactors], sumInt) # vector with si values in %

# test anova
if (sum(si_Out1) < 99.9 | sum(df_ss$SS_p) > 100.1) {
  print("Check your ANOVA")
  print(paste0("Sum of all % of Si: ", sum(df_ss$SS_p))) # check it
  }

# Create the Si dataframe and graph it
df_si <- data.frame(si_Out1)
rownames(df_si) <- gsub(" ","",c(mainFactNames[1:noFactors], "Interactions"))

df_si$FactorName <- rownames(df_si)
colnames(df_si) <- c("PercTotal_SS", "FactorName") 


  # Add labels
  df_si <- data.frame(thisCrop = thisDf$Crop[1],
                   thisStage = thisDf$Stage[1],
                   thisIrrig = thisDf$Irrigation[1],
                   si_Out1[1], 
                   si_Out1[2], 
                   si_Out1[3],
                   si_Out1[4]
                   )
 
 noLabels <- 3 # FIXME: do it prittier later

  # label Si df FIXME: Automate this
  colnames(df_si)[noLabels+1] <- gsub(" ","",paste0(mainFactNames[1]))
  colnames(df_si)[noLabels+2] <- gsub(" ","",paste0(mainFactNames[2]))
  colnames(df_si)[noLabels+3] <- gsub(" ","",paste0(mainFactNames[3]))
  colnames(df_si)[noLabels+4] <- "Interactions"
  
  # Appends to final Si df
  if(i==1){ # FIXME: Untested
    si_df_final <- data.frame(df_si)  
    } else {
    si_df_final <- rbind(si_df_final, df_si)
    }

}

summary(si_df_final)

```

## give some numbers in table

```{r}
si_df_final %>%
  tidyr::gather("Si_Item","Si_Value", SurfaceKl:Interactions) %>%
  group_by(Si_Item,thisCrop,thisStage) %>%
  dplyr::select(- thisIrrig)%>%
  summarise_each(funs(min,max)) %>%
  kable(digits=2)
```


## 

```{r, fig.height=8,fig.width=10, echo=FALSE}

si_df_final$thisIrrig <- factor(si_df_final$thisIrrig, levels=c("No Irrigation",
                                 "Low Frequency",
                                 "Medium Frequency", 
                                 "High Frequency"))

si_df_final %>%
  tidyr::gather("Si_Item","Si_Value", SurfaceKl:Interactions) %>%
  mutate(Si_Item = factor(Si_Item, levels = c("SurfaceKl",
                                 "KLReduction",
                                 "RootFrontVelocity", 
                                 "Interactions")
                          )) %>%
  ggplot(aes(x=rev(thisIrrig), y=Si_Value, fill=factor(Si_Item))) +
  geom_bar(stat="identity") +
  facet_grid(thisCrop~thisStage) +
  ylab("Sensitivity index (%)") +
  xlab(" Water supply treatment") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) + theme(legend.title=element_blank()) +
  theme(text = element_text(size=16))
```




```{r}




 do (anova = aov(Pred ~ SurfaceKl*KLReduction*RootFrontVelocity, data = .))
anova_SS <- summary(anova)[[1]]$'Sum Sq'

# do an anova for each pixel 
# This loop takes ages!

si_df_final <- NULL
si_df_final_m <- NULL


pixels <- unique(workDF$pixel_ID)

summary(workDF) # Should I use workDF?
head(workDF)

vars <- c("TotalBiomass", "HarvestIndex")

# FIXME: Loop is too slow - do this later with dplyr or something better

for (v in 1:length(vars)) {
  for (p in 1:length(pixels)) {
  # for (p in 1:10) { # test

  thisPixDF <- workDF %>%
    filter(pixel_ID == pixels[[p]]) %>%
    group_by(thisHyb, thisSow, yearAsFact, row, col, thisLat, thisLong, Combine) %>% # to avoid crops that are harvested in same year (for anova)
    dplyr::select(TotalBiomass, HarvestIndex) %>%
    summarise_each(funs(mean))

 # write.table(thisPixDF, file = "test.txt")
  head(thisPixDF)
  summary(thisPixDF)

  # do anova (FIXME: do more elegant)
  if (vars[v] == "TotalBiomass") {
  anova <- aov(TotalBiomass ~ thisHyb*thisSow*yearAsFact, data = thisPixDF)
  } else if (vars[v] == "HarvestIndex") {
  anova <- aov(HarvestIndex ~ thisHyb*thisSow*yearAsFact, data = thisPixDF)
  }

  anovaTable <- summary(anova)
  anovaTable
  
  #Retrive SS and MS values
  anova_SS <- anovaTable[[1]]$'Sum Sq'
 # anova_MS <- anovaTable[[1]]$'Mean Sq' 

  # Binds all SS for each variable together into a new df
 # df_ss <- data.frame(SS = anova_SS, MS = anova_MS)
  df_ss <- NULL
  df_ss <- data.frame(SS = anova_SS)

  #retrieves row names and load into result df
  namesAnTab <- rownames(anovaTable[[1]])
  rownames (df_ss) <- gsub(" ","",namesAnTab) # remove spaces
 
 # get names and count of main factors
 mainFactNames <- rownames (df_ss)[-grep(':',rownames (df_ss))] # isolate the main factors from
 noFactors <- length(mainFactNames)  # counts row names that do not have ":" i.e. from interaction
 
 # Creates a column with "normalised" percent of total variation (SS) 
  # in relation to total SS for each factor in that pixel
  df_ss$SS_p <- round((df_ss$SS/sum(df_ss$SS))*100,3)
  # df_ss$MS_p <- round((df_ss$MS/sum(df_ss$MS))*100,3) 
  # FIXME: Not sure which to use SS or MS - Esther Menkeen suggested SS
  # ifelse(sum(df_ss$SS_p>101|df_ss$SS_p>99),print("Check ANOVA sum"),"All good")
 
# Add SS of interections as a new vector element that adds to 100%
sumInt <- sum(df_ss$SS_p[(noFactors+1):length(namesAnTab)]) # Calculate sums total SS due to interactions (i.e. sums every SS that is not main factor)
si_Out1 <- c(df_ss$SS_p[1:noFactors], sumInt) # vector with si values in %

# test anova
if (sum(si_Out1) < 99.9 | sum(df_ss$SS_p) > 100.1) {
  print("Check your ANOVA")
  print(paste0("Sum of all % of Si: ", sum(df_ss$SS_p))) # check it
  }

# Create the Si dataframe and graph it
df_si <- data.frame(si_Out1)
rownames(df_si) <- gsub(" ","",c(mainFactNames[1:noFactors], "Interactions"))

df_si$FactorName <- rownames(df_si)
colnames(df_si) <- c("PercTotal_SS", "FactorName") 

  # Using SS instead of MS as suggested by Esther Menkeen
  df_si <- data.frame(thisLat = thisPixDF$thisLat[1],
                   thisLong = thisPixDF$thisLong[1],
                #   thisRegion = thisPixDF$region[1],
                   thisClimZone = thisPixDF$Combine[1],
                   thisVar = vars[v],
                   row = thisPixDF$row[1],
                   col = thisPixDF$col[1],
                   si_Out1[1], 
                   si_Out1[2], 
                   si_Out1[3],
                   si_Out1[4]
                   )
 
 noLabels <- 6 # FIXME: do it prittier later

  # label Si df FIXME: Automate this
  colnames(df_si)[noLabels+1] <- gsub(" ","",paste0("Si_",mainFactNames[1]))
  colnames(df_si)[noLabels+2] <- gsub(" ","",paste0("Si_",mainFactNames[2]))
  colnames(df_si)[noLabels+3] <- gsub(" ","",paste0("Si_",mainFactNames[3]))
  colnames(df_si)[noLabels+4] <- "Si_Interac"
  
  # Appends to final Si df
 # if(p==1 & vars[v] == 1){ # FIXME: This seems not right v==1 ?
  if(p==1){ # FIXME: Untested

    si_df_final <- data.frame(df_si)  
    } else {
    si_df_final <- rbind(si_df_final, df_si)
    }
 print(paste0("Variable: ", vars[v], "and pixel: ",p))
}

head(si_df_final)
nrow(si_df_final)

# Graph Si for eacj main factor and interaction
#gH <- ggplot(si_df_final, aes(x=Si_thisHyb)) + geom_histogram(binwidth=.5, colour="black", fill="white")
#gS <- ggplot(si_df_final, aes(x=Si_thisSow)) + geom_histogram(binwidth=.5, colour="black", fill="white")
#gW <- ggplot(si_df_final, aes(x=Si_yearAsFact)) + geom_histogram(binwidth=.5, colour="black", fill="white")
#gI <- ggplot(si_df_final, aes(x=Si_Interac)) + geom_histogram(binwidth=.5, colour="black", fill="white")

# append variables in single df
si_df_final_m <- rbind(si_df_final_m, si_df_final) # place holder while we decide what to do with region

summary(si_df_final_m)

} # end loop in variables


# save this DF (each Si by Pixel here) 
write.table(si_df_final_m, file=paste0("Si_by_Pixel.txt"), row.names=FALSE, col.names=TRUE, sep=" ",append=FALSE, quote=FALSE)
```


```{r}
si_df_final_m <- read.table("Si_by_Pixel.txt", header = TRUE) 

si_df_final_m$thisClimZone <- factor(si_df_final_m$thisClimZone, levels = c('LTLR', 'LTMR', 'LTHR','MTLR','MTMR', 'MTHR','HTLR', 'HTMR', 'HTHR'))

# ---- All plotted together by clim zone -------------------------

fontSize <- 16
hg1 <- si_df_final_m %>%
  filter(thisVar == "TotalBiomass")  %>%
  group_by(thisLat, thisLong) %>%
  gather(factName, siVal, 7:10) %>% # FIXME: this might change - can you automate?
  ggplot(aes(x= siVal, colour=factName, fill=factName)) + 
  geom_histogram(aes(y=..density..), binwidth=.8, alpha=0) +
 # geom_histogram(binwidth=1, alpha=0) +
  geom_density(alpha=0.2,size=1.5) +
  facet_grid(thisVar~.) +
  facet_wrap(~thisClimZone, scales="free") +
  xlab("Percent of total variability (%)") +
  ylab("Frequency distribution") +
  theme(text = element_text(size=fontSize)) + 
  theme(legend.position = "none")
#  ggsave(file=paste0("Bio_Si_hist.tiff"), dpi = 300)

# Harvest index

hg2 <- si_df_final_m %>%
  filter(thisVar == "HarvestIndex")  %>%
  group_by(thisLat, thisLong) %>%
  gather(factName, siVal, 7:10) %>% # FIXME: this might change - can you automate?
  ggplot(aes(x= siVal, colour=factName, fill=factName)) + 
  geom_histogram(aes(y=..density..), binwidth=.8, alpha=0) +
 # geom_histogram(binwidth=1, alpha=0) +
  geom_density(alpha=0.2,size=1.5) +
  facet_grid(thisVar~.) +
  facet_wrap(~thisClimZone, scales="free") +
  xlab("Percent of total variability (%)") +
  ylab("Frequency distribution") +
  theme(text = element_text(size=fontSize)) + 
  theme(legend.position = "none")
#  ggsave(file=paste0("HI_Si_hist.tiff"), dpi = 300)

grid.arrange(hg1, hg2, nrow=2) # save it via rstudio

#-----------------------------------------------------
# Bar graph version (pooled by climate zones) --------

# Biomass - bar

cZpallete <- c("#ca0020","#f4a582","#92c5de","#0571b0")

fontSize <- 18

bg1 <- si_df_final_m %>%
  filter(thisVar == "TotalBiomass")  %>%
  group_by(thisClimZone) %>%
  summarise_each(funs(mean)) %>%
  mutate (Si_tot = Si_thisHyb + Si_thisSow + Si_yearAsFact + Si_Interac) %>%
  mutate (Si_thisHyb = Si_thisHyb/Si_tot*100, 
          Si_thisSow = Si_thisSow/Si_tot*100, 
          Si_yearAsFact = Si_yearAsFact/Si_tot*100, 
          Si_Interac = Si_Interac/Si_tot*100) %>%
  gather(factName, siVal, 7:10) %>% # FIXME: Automate this
  ggplot(aes(x=thisClimZone, y=siVal, fill=factName, order=factName)) + 
  geom_bar(stat='identity')  +
  xlab(" ") + 
  ylab("Share of total variability (%)") + 
  scale_fill_discrete(name="Factor",
                         labels=c("Hybrid", "Sowing dates", "Weather" , "Interactions"))+
  theme(text = element_text(size=fontSize)) +
 # theme(legend.position="bottom") +
  ggtitle("(a) Total biomass") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) # +
 # geom_text(aes(label = paste0("(",round(df_av$siVal, digits=1),"%)"), y=mean(siVal)), size = 7) +
#  ggsave(file=paste0("Bio_Si_barGraph.tiff"), dpi = 300)

# Harvest Index - bar

bg2 <- si_df_final_m %>%
#   filter(thisVar == "TotalBiomass")  %>%
  filter(thisVar == "HarvestIndex")  %>%
  group_by(thisClimZone) %>%
  summarise_each(funs(mean)) %>%
  mutate (Si_tot = Si_thisHyb + Si_thisSow + Si_yearAsFact + Si_Interac) %>%
  mutate (Si_thisHyb = Si_thisHyb/Si_tot*100, 
          Si_thisSow = Si_thisSow/Si_tot*100, 
          Si_yearAsFact = Si_yearAsFact/Si_tot*100, 
          Si_Interac = Si_Interac/Si_tot*100) %>%
  gather(factName, siVal, 7:10) %>% # FIXME: Automate this
  ggplot(aes(x=thisClimZone, y=siVal, fill=factName, order=factName)) + 
  geom_bar(stat='identity')  +
  ggtitle("(b) Harvest index") +
  xlab("Climatic zones ") + ylab("Share of total variability (%)") + 
  scale_fill_discrete(name="Factor",
                         labels=c("Hybrid", "Sowing dates", "Weather" , "Interactions"))+
  theme(text = element_text(size=fontSize)) +
#  theme(legend.position="none") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) # +
 # geom_text(aes(label = paste0("(",round(df_av$siVal, digits=1),"%)"), y=mean(siVal)), size = 7) +
  ggsave(file=paste0("HI_Si_barGraph.tiff"), dpi = 300)

grid.arrange(bg1, bg2, nrow=2) # save it via rstudio
```

